routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\User\OrderController;
use App\Http\Controllers\Admin\SalesController;
use App\Http\Controllers\Admin\TaxesController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\User\SearchController;
use App\Http\Controllers\Admin\OrdersController;
use App\Http\Controllers\Admin\StatesController;
use App\Http\Controllers\User\API\UserController;
use App\Http\Controllers\User\ProductsController;
use App\Http\Controllers\User\API\StateController;
use App\Http\Controllers\Admin\AdminHomeController;
use App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\User\API\AddressController;
use App\Http\Controllers\User\API\BillingController;
use App\Http\Controllers\User\UserAccountController;
use App\Http\Controllers\Admin\API\TaxesAPIController;
use App\Http\Controllers\Admin\API\OrdersAPIController;
use App\Http\Controllers\Admin\API\StatesAPIController;
use App\Http\Controllers\Admin\API\ProductsAPIController;
use App\Http\Controllers\User\API\ShoppingCartController;
use App\Http\Controllers\Admin\API\CategoriesAPIController;
use App\Http\Controllers\Auth\RegisterValidationController;
use App\Http\Controllers\User\API\OrderController as ApiOrderController;
use App\Http\Controllers\User\API\SearchController as ApiSearchController;
use App\Http\Controllers\Admin\ProductsController as AdminProductsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Auth routes
Route::get('logout', [LoginController::class, 'logout'])->name('user.logout');
Auth::routes();

//Register User
Route::post('user-email-taken', [RegisterValidationController::class, 'email'])->name('register.user.email');
Route::post('user-username-taken', [RegisterValidationController::class, 'username'])->name('register.user.username');
Route::get('get-states', [StateController::class, 'index'])->name('user.states');

// Home Routes
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('about', [HomeController::class, 'about'])->name('about');
Route::get('contact', [HomeController::class, 'contact'])->name('contact');
Route::get('view-product/{title}', [ProductsController::class, 'show'])->name('product.show');

// Search
Route::get('product/{category}', [SearchController::class, 'category'])->name('search.product.category');
Route::post('products', [SearchController::class, 'scout'])->name('search.products');
Route::get('products/{search}', [SearchController::class, 'show'])->name('search.products.search');
Route::post('products/api', [ApiSearchController::class, 'store'])->name('search.products.api');

// Shopping Cart Routes
Route::post('shopping-cart/add', [ShoppingCartController::class, 'store'])->name('shopping.cart.add');
Route::post('shopping-cart/remove', [ShoppingCartController::class, 'destroy'])->name('shopping.cart.destroy');
Route::post('shopping-cart/update', [ShoppingCartController::class, 'update'])->name('shopping.cart.update');
Route::get('shopping-cart/get', [ShoppingCartController::class, 'index'])->name('shopping.cart');

//User Account
Route::get('user/user-account', [UserAccountController::class, 'index'])->name('user.account');
Route::get('user/user-account/order/{id}', [UserAccountController::class, 'show'])->name('user.account.order');
Route::get('user/users-details', [UserController::class, 'index'])->name('users.details');

//orders Page
Route::get('/order/{stage}', [OrderController::class, 'index'])->name('order.index');
Route::post('/order', [ApiOrderController::class, 'store'])->name('order.add.api');
Route::patch('/order/{order}', [ApiOrderController::class, 'update'])->name('order.update.api');
Route::post('/order/billing-form', [BillingController::class, 'store'])->name('order.billing.post');
Route::resource('user/address', AddressController::class);

//orders API
Route::get('/order/invoice/{order}', [ApiOrderController::class, 'show'])->name('order.invoice.api');

/*
|--------------------------------------------------------------------------
| Admin Section
|--------------------------------------------------------------------------
| The following routes are from the admin section of Lara-Commerce.  In order
| to access these pages the user must have admin privileges.
*/
Route::group(['as' => 'admin.'], function(){
    Route::get('admin', [AdminHomeController::class, 'index'])->name('user.account');;

    //Products
    Route::resource('admin/products', AdminProductsController::class);
    Route::post('admin/products/image/{product}', [ProductsAPIController::class, 'image'])->name('products.image.api');
    Route::get('admin/products-api/', [ProductsAPIController::class, 'index'])->name('products.api');


    // Sales
    Route::resource('admin/products/sales', SalesController::class);

    // Users
    Route::get('admin/users', [UsersController::class, 'index'])->name('users');;
    Route::get('admin/users/addresses/{user}', [UsersController::class, 'addresses'])->name('user.address');
    Route::get('admin/users/orders/{user}', [UsersController::class, 'orders'])->name('user.orders');

    // Orders
    Route::get('admin/orders', [OrdersController::class, 'index'])->name('orders');
    Route::get('admin/orders/{id}', [OrdersController::class, 'show'])->name('order');
    Route::get('admin/orders/view/{order}', [OrdersAPIController::class, 'show'])->name('order.show.api');
    Route::post('admin/orders/view/{order}', [OrdersAPIController::class, 'store'])->name('order.add.api');

    // Categories
    Route::get('admin/categories', [CategoriesController::class, 'index'])->name('categories');
    Route::resource('admin/api/categories', CategoriesAPIController::class);

    //Taxes
    Route::get('admin/taxes', [TaxesController::class, 'index'])->name('taxes');
    Route::get('admin/api/taxes/all', [TaxesAPIController::class, 'all'])->name('taxes.all.api');
    Route::resource('admin/api/taxes', TaxesAPIController::class);

    //States
    Route::get('admin/states', [StatesController::class, 'index'])->name('states');
    Route::resource('admin/api/states', StatesAPIController::class, ['only' => [
        'index', 'store', 'update', 'destroy'
    ]]);
});
Route::get('/test', function(){
    dd(\Illuminate\Support\Facades\Schema::hasTable('roles'));

    return view('test');
});


Route::post('/test', function(\Illuminate\Http\Request $request){


})->middleware('ajax.auth');;

// Route::prefix('auth')->group( function (){
//     Route::get('login', 'AppController@login');
//     Route::get('register', 'AppController@register');
//     Route::get('logout', 'AppController@logout');
// });

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/_includes/_ecommerce/_carousel.blade.php
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="ecommerce-carousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="{{ asset('images/headerimagescale.jpg') }}" alt="Image header of sale">
                </div>
                <div class="item">
                    <img class="slide-image"  src="{{ asset('images/headerimagescale2.jpg') }}" alt="Image header of sale two">
                </div>
            </div><!-- /.carousel-indicators -->
            <a class="left carousel-control" href="#ecommerce-carousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#ecommerce-carousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div><!-- /.carousel-example-generic -->
    </div><!-- /.col -->
</div><!-- /.row -->

resources/views/_includes/_ecommerce/_footer.blade.php
<div class="container">
    <hr>
    <footer>
        <div class="row">
            <div class="col-sm-4">
                <p>Copyright &copy;Shawn Legge</p>
            </div><!-- /.col -->
            <div class="col-sm-4">
                <a href="http://www.freepik.com">Designed by Freepik</a>
                <a href="https://www.freepik.com/free-vector/wavy-summer-sale-banners-with-photo_2212854.htm">Designed by Freepik</a>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </footer>
</div><!-- /.footer -->

resources/views/_includes/_ecommerce/_messages.blade.php
@if(isset($errors) && count($errors) > 0)
    <div class="help-block alert alert-danger">
        @foreach($errors->all() as $error)
            <p>{{ $error }}</p>
        @endforeach
    </div><!-- /.help-block -->
@endif

resources/views/_includes/_ecommerce/_navbar.blade.php
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div><!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <search-products>

                </search-products>
                <li>
                    <a href="{{ route('home') }}">Home</a>
                </li>
                <li>
                    <a href="{{ route('about') }}">About</a>
                </li>
                <li>
                    <a href="{{ route('contact') }}">Contact</a>
                </li>
                @if($isAdmin)
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="admin-page">Admin Page<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('admin.user.account') }}">Home Page</a></li>
                            <li><a href="{{ route('admin.users') }}">Users Page</a></li>
                            <li><a href="{{ route('admin.products.index') }}">Products Page</a></li>
                            <li><a href="{{ route('admin.orders') }}">Orders Page</a></li>
                            <li><a href="{{ route('admin.categories') }}">Categories Page</a></li>
                            <li><a href="{{ route('admin.taxes') }}">Taxes Page</a></li>
                            <li><a href="{{ route('admin.states') }}">States Page</a></li>
                        </ul>
                    </li>
                @endif
                <categories-navbar v-if="!show.showSideBar"
                                   :categories="{{ $categories }}">

                </categories-navbar>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <navbar-cart :cart="cart"
                             @remove-item="removeItem"
                             @update-quantity="updateCart">

                </navbar-cart>
                @if (Auth::guest())
                    <li>
                        <a href="{{ route('login') }}">
                            <i class="fa fa-sign-in" aria-hidden="true"></i>
                            Login
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('register') }}">
                            <i class="fa fa-registered" aria-hidden="true"></i>
                            Register
                        </a>
                    </li>
                @else
                    <li class="dropdown" id="user-account">
                        <a href="#" class="dropdown-toggle"
                           data-toggle="dropdown"
                           role="button"
                           aria-expanded="false">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            {{ Auth::user()->name }}'s Account
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ route('user.account') }}"> My Account </a></li>
                            <li><a href="{{ route('user.logout') }}">Logout</a></li>
                        </ul>
                    </li>
                @endif
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
</nav>

resources/views/_includes/_ecommerce/_sidebar.blade.php
<p class="lead">Lara-Commerce</p>
<div class="list-group" v-if="show.showSideBar">
    @foreach($categories as $category)
        <a class="list-group-item {{ (isset($search ) && $search === $category->name) ? 'active' : '' }}"
           href="{{ route('search.product.category' , ['category' => $category->name ]) }}">
            {{ $category->name }}
        </a>
    @endforeach
</div>