routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\User\OrderController;
use App\Http\Controllers\Admin\SalesController;
use App\Http\Controllers\Admin\TaxesController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\User\SearchController;
use App\Http\Controllers\Admin\OrdersController;
use App\Http\Controllers\Admin\StatesController;
use App\Http\Controllers\User\API\UserController;
use App\Http\Controllers\User\ProductsController;
use App\Http\Controllers\User\API\StateController;
use App\Http\Controllers\Admin\AdminHomeController;
use App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\User\API\AddressController;
use App\Http\Controllers\User\API\BillingController;
use App\Http\Controllers\User\UserAccountController;
use App\Http\Controllers\Admin\API\TaxesAPIController;
use App\Http\Controllers\Admin\API\OrdersAPIController;
use App\Http\Controllers\Admin\API\StatesAPIController;
use App\Http\Controllers\Admin\API\ProductsAPIController;
use App\Http\Controllers\User\API\ShoppingCartController;
use App\Http\Controllers\Admin\API\CategoriesAPIController;
use App\Http\Controllers\Auth\RegisterValidationController;
use App\Http\Controllers\User\API\OrderController as ApiOrderController;
use App\Http\Controllers\User\API\SearchController as ApiSearchController;
use App\Http\Controllers\Admin\ProductsController as AdminProductsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Auth routes
Route::get('logout', [LoginController::class, 'logout'])->name('user.logout');
Auth::routes();

//Register User
Route::post('user-email-taken', [RegisterValidationController::class, 'email'])->name('register.user.email');
Route::post('user-username-taken', [RegisterValidationController::class, 'username'])->name('register.user.username');
Route::get('get-states', [StateController::class, 'index'])->name('user.states');

// Home Routes
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('about', [HomeController::class, 'about'])->name('about');
Route::get('contact', [HomeController::class, 'contact'])->name('contact');
Route::get('view-product/{title}', [ProductsController::class, 'show'])->name('product.show');

// Search
Route::get('product/{category}', [SearchController::class, 'category'])->name('search.product.category');
Route::post('products', [SearchController::class, 'scout'])->name('search.products');
Route::get('products/{search}', [SearchController::class, 'show'])->name('search.products.search');
Route::post('products/api', [ApiSearchController::class, 'store'])->name('search.products.api');

// Shopping Cart Routes
Route::post('shopping-cart/add', [ShoppingCartController::class, 'store'])->name('shopping.cart.add');
Route::post('shopping-cart/remove', [ShoppingCartController::class, 'destroy'])->name('shopping.cart.destroy');
Route::post('shopping-cart/update', [ShoppingCartController::class, 'update'])->name('shopping.cart.update');
Route::get('shopping-cart/get', [ShoppingCartController::class, 'index'])->name('shopping.cart');

//User Account
Route::get('user/user-account', [UserAccountController::class, 'index'])->name('user.account');
Route::get('user/user-account/order/{id}', [UserAccountController::class, 'show'])->name('user.account.order');
Route::get('user/users-details', [UserController::class, 'index'])->name('users.details');

//orders Page
Route::get('/order/{stage}', [OrderController::class, 'index'])->name('order.index');
Route::post('/order', [ApiOrderController::class, 'store'])->name('order.add.api');
Route::patch('/order/{order}', [ApiOrderController::class, 'update'])->name('order.update.api');
Route::post('/order/billing-form', [BillingController::class, 'store'])->name('order.billing.post');
Route::resource('user/address', AddressController::class);

//orders API
Route::get('/order/invoice/{order}', [ApiOrderController::class, 'show'])->name('order.invoice.api');

/*
|--------------------------------------------------------------------------
| Admin Section
|--------------------------------------------------------------------------
| The following routes are from the admin section of Lara-Commerce.  In order
| to access these pages the user must have admin privileges.
*/
Route::group(['as' => 'admin.'], function(){
    Route::get('admin', [AdminHomeController::class, 'index'])->name('user.account');;

    //Products
    Route::resource('admin/products', AdminProductsController::class);
    Route::post('admin/products/image/{product}', [ProductsAPIController::class, 'image'])->name('products.image.api');
    Route::get('admin/products-api/', [ProductsAPIController::class, 'index'])->name('products.api');


    // Sales
    Route::resource('admin/products/sales', SalesController::class);

    // Users
    Route::get('admin/users', [UsersController::class, 'index'])->name('users');;
    Route::get('admin/users/addresses/{user}', [UsersController::class, 'addresses'])->name('user.address');
    Route::get('admin/users/orders/{user}', [UsersController::class, 'orders'])->name('user.orders');

    // Orders
    Route::get('admin/orders', [OrdersController::class, 'index'])->name('orders');
    Route::get('admin/orders/{id}', [OrdersController::class, 'show'])->name('order');
    Route::get('admin/orders/view/{order}', [OrdersAPIController::class, 'show'])->name('order.show.api');
    Route::post('admin/orders/view/{order}', [OrdersAPIController::class, 'store'])->name('order.add.api');

    // Categories
    Route::get('admin/categories', [CategoriesController::class, 'index'])->name('categories');
    Route::resource('admin/api/categories', CategoriesAPIController::class);

    //Taxes
    Route::get('admin/taxes', [TaxesController::class, 'index'])->name('taxes');
    Route::get('admin/api/taxes/all', [TaxesAPIController::class, 'all'])->name('taxes.all.api');
    Route::resource('admin/api/taxes', TaxesAPIController::class);

    //States
    Route::get('admin/states', [StatesController::class, 'index'])->name('states');
    Route::resource('admin/api/states', StatesAPIController::class, ['only' => [
        'index', 'store', 'update', 'destroy'
    ]]);
});
Route::get('/test', function(){
    dd(\Illuminate\Support\Facades\Schema::hasTable('roles'));

    return view('test');
});


Route::post('/test', function(\Illuminate\Http\Request $request){


})->middleware('ajax.auth');;

// Route::prefix('auth')->group( function (){
//     Route::get('login', 'AppController@login');
//     Route::get('register', 'AppController@register');
//     Route::get('logout', 'AppController@logout');
// });

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/_includes/_tables/_categories.blade.php
<div class="page-header">
    <h1>Categories Page</h1>
</div>
<div class="col-sm-4 col-sm-offset-3">
    <div class="well">
        <category-form>

        </category-form>
    </div>
</div><!-- /.col -->
<categories-table>

</categories-table>

resources/views/admin/_includes/_tables/_orders.blade.php
<div class="page-header">
    <h1>Orders Page</h1>
</div>
<table class="table">
    <thead>
    <tr>
        <th>Order ID</th>
        <th>User</th>
        <th>Total</th>
        <th>Items Ordered</th>
        <th>View</th>
    </tr>
    </thead>
    <tbody>
    @foreach($orders as $order)
        <tr>
            <td>
                <span class="table-element">{{ $order->id }}</span>
            </td>
            <td>
                <span class="table-element">{{ $order->user->fullName() }}</span>
            </td>
            <td>
                <span class="table-element">{{ $order->total }}</span>
            </td>
            <td>
                <span class="table-element">{{ $order->products->count() }}</span>
            </td>
            <td>
                <a class="btn btn-primary" href="{{ route('admin.order', ['id' => $order->id]) }}">View</a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
<div class="row">
    <div class="mid_center">
        {{ $orders->links() }}
    </div>
</div><!-- /.row -->

resources/views/admin/_includes/_tables/_products.blade.php
<div class="page-header">
    <h1>Products Page</h1>
</div>
<product-table>

</product-table>

resources/views/admin/_includes/_tables/_states.blade.php
<div class="page-header">
    <h1>States Page</h1>
</div>
<states-table>

</states-table>

resources/views/admin/_includes/_tables/_taxes.blade.php
<div class="page-header">
    <h1>Taxes Page</h1>
</div>
<tax-table>

</tax-table>

resources/views/admin/_includes/_tables/_users.blade.php
<div class="page-header">
    <h1>Users Page</h1>
</div>
<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Addresses</th>
        <th>Orders</th>
    </tr>
    </thead>
    <tbody>
        @foreach($users as $user)
            <tr>
                <td>
                    <span class="table-element">{{ $user->id }}</span>
                </td>
                <td>
                    <span class="table-element">{{ $user->first_name }}</span>
                </td>
                <td>
                    <span class="table-element">{{ $user->last_name }}</span>
                </td>
                <td>
                    <span class="table-element">{{ $user->email }}</span>
                </td>
                <td>
                    <a href="{{ route('admin.user.address', ['user' => $user->id]) }}" class="btn btn-primary">Addresses</a>
                </td>
                <td>
                    <a href="{{ route('admin.user.orders', ['user' => $user->id]) }}" class="btn btn-primary">Orders</a>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>
<div class="row">
    <div class="mid_center">
        {{ $users->links() }}
    </div>
</div><!-- /.row -->

resources/views/admin/_includes/_tables/_usersAddresses.blade.php
<div class="page-header">
    <h1>Users Addresses</h1>
    <h3>     Addresses for {{ $user->fullName() }}</h3>
</div>
@if($user->addresses->count() > 0)
<table class="table">
    <thead>
    <tr>
        <th>Street Address</th>
        <th>State</th>
        <th>City</th>
        <th>Postal Code</th>
    </tr>
    </thead>
    <tbody>
        @foreach($user->addresses as $address)
            <tr>
                <td class="table-element">{{ $address->address }}</td>
                <td class="table-element">{{ $address->state->abbreviation }}</td>
                <td class="table-element">{{ $address->city }}</td>
                <td class="table-element">{{ $address->postal_code }}</td>
            </tr>
        @endforeach
    </tbody>
</table>
@else
    <h4>There are no records for any addresses for this user</h4>
@endif

resources/views/admin/_includes/_tables/_usersOrders.blade.php
<div class="page-header">
    <h1>Users Orders</h1>
    <h3>Orders for {{ $user->fullName() }}</h3>
</div>
@if($user->orders->count() > 0)
    <table class="table">
        <thead>
        <tr>
            <th>Order ID</th>
            <th>User</th>
            <th>Total</th>
            <th>Items Ordered</th>
            <th>Shipped</th>
            <th>View</th>
        </tr>
        </thead>
        <tbody>
        @foreach($user->orders as $order)
            <tr>
                <td class="table-element">{{ $order->id }}</td>
                <td class="table-element">{{ $user->fullName() }}</td>
                <td class="table-element">{{ $order->total }}</td>
                <td class="table-element">{{ $order->products->count() }}</td>
                <td class="table-element">{{ $order->shipped }}</td>
                <td><a class="btn btn-primary" href="">View Order</a></td>
            </tr>
        @endforeach
        </tbody>
    </table>
@else
    <h4>There are no records for any addresses for this user</h4>
@endif